### ISSUE TITLE
Client example code doesn't work, results in ImportError, and then TypeError

### ISSUE THREAD

**Issue by dvtan** [RobertoPrevato/BlackSheep#14] opened 2019-06-23 07:13 UTC
When running the client like this: 

```
import asyncio
from blacksheep.client import ClientSession

async def client_example():
    async with ClientSession() as client:
        response = await client.get('https://docs.python.org/3/')
        text = await response.text()
        print(text)

loop = asyncio.get_event_loop()
loop.run_until_complete(client_example())
```

There is an ImportError:

```
  File "/venv/webapp/lib/python3.7/site-packages/blacksheep/server/application.py", line 22, in <module>
    from blacksheep.middlewares import get_middlewares_chain
ImportError: cannot import name 'get_middlewares_chain' from 'blacksheep.middlewares' (/home/david/venv/api/lib/python3.7/site-packages/blacksheep/middlewares.py)
```

I don't understand why Python is giving this error, since the server example code runs fine, and I see the code for `get_middlewares_chain`  in `middlewares.py` actually exists. But even trying to import it in an empty python console gets the same error.

I temporarily copied the code from `get_middlewares_chain` into `application.py` to try again, and there's no import error this time, but now there is a TypeError:

```
Traceback (most recent call last):
  File "/venv/webapp/lib/python3.7/site-packages/blacksheep/client/pool.py", line 58, in get_connection
    return self._get_connection()
  File "/venv/webapp/lib/python3.7/site-packages/blacksheep/client/pool.py", line 41, in _get_connection
    connection = self._idle_connections.get_nowait()  # type: ClientConnection
  File "/usr/lib/python3.7/asyncio/queues.py", line 182, in get_nowait
    raise QueueEmpty
asyncio.queues.QueueEmpty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/data/src/ochous-api/asdf/await.py", line 13, in <module>
    loop.run_until_complete(client_example())
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "/mnt/data/src/ochous-api/asdf/await.py", line 7, in client_example
    response = await client.get('https://docs.python.org/3/')
  File "/venv/webapp/lib/python3.7/site-packages/blacksheep/client/session.py", line 324, in get
    None))
  File "/venv/webapp/lib/python3.7/site-packages/blacksheep/client/session.py", line 281, in send
    return await self._handler(request)
  File "/venv/webapp/lib/python3.7/site-packages/blacksheep/middlewares.py", line 6, in middleware_wrapper
    return await handler(request, next_handler)
  File "/venv/webapp/lib/python3.7/site-packages/blacksheep/client/cookies.py", line 285, in cookies_middleware
    response = await next_handler(request)
  File "/venv/webapp/lib/python3.7/site-packages/blacksheep/client/session.py", line 130, in root_handler
    return await self._send_core(request)
  File "/venv/webapp/lib/python3.7/site-packages/blacksheep/client/session.py", line 289, in _send_core
    response = await self._send_using_connection(request)
  File "/venv/webapp/lib/python3.7/site-packages/blacksheep/client/session.py", line 302, in _send_using_connection
    connection = await self.get_connection(request.url)
  File "/venv/webapp/lib/python3.7/site-packages/blacksheep/client/session.py", line 257, in get_connection
    loop=self.loop)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/venv/webapp/lib/python3.7/site-packages/blacksheep/client/pool.py", line 60, in get_connection
    return await self.create_connection()
  File "/venv/webapp/lib/python3.7/site-packages/blacksheep/client/pool.py", line 68, in create_connection
    ssl=self.ssl)
  File "uvloop/loop.pyx", line 1782, in create_connection
  File "uvloop/sslproto.pyx", line 237, in uvloop.loop.SSLProtocol.__init__
TypeError: Expected unicode, got bytes
```

**Comment by RobertoPrevato** [comment] 2019-06-23 08:27
@dvtan, Thank you for opening this issue!
I just resolved the issue, and published a new package to PyPi, can you please update using this command;

```bash
pip install blacksheep -U
```

The issue was caused by an accidental circular import I introduced recently. It was resolved by extracting and putting in a dedicated module a function that is required by both client and server.

Of course I need to add more tests to this project, I am working on this; but also on several other things at the same time. I will soon publish a roadmap for BlackSheep.

**Closed** 2019-06-23 18:01 UTC
