### ISSUE TITLE
Uvicorn setup change

### ISSUE THREAD

**Issue by waghanza** [RobertoPrevato/BlackSheep#59] opened 2020-12-10 11:19 UTC
Hi @RobertoPrevato,

I can see you ping `uvicorn` version in `requirements.txt`.
https://github.com/RobertoPrevato/BlackSheep/blob/a0bacc8c28f7a6158b73e21f8096bb73949c2406/requirements.txt#L46

The setup of this dependency changes for `0.12`, see https://github.com/encode/uvicorn/blob/master/CHANGELOG.md#0120---2020-09-28

Regards,

**Comment by RobertoPrevato** [comment] 2020-12-10 13:14
Hi @waghanza 
Thank you for the heads up, I will update soon the dependency.

Note: requirements.txt is used when running tests during the build pipeline, however when installing the package from pypi the only thing that matters is the `install_requires` section in the `setup.py`. `setup.py` doesn't include `uvicorn`, since it's possible to use blacksheep with other kinds of ASGI servers.

I will soon create a PR to update this dependency in `requirements.txt` to verify that all tests pass.

**Comment by waghanza** [comment] 2020-12-10 13:37
Then I do not understand https://the-benchmarker.semaphoreci.com/jobs/1fc7fd44-8041-46b8-b8e7-713d965e5b02

`blacksheep` is failing on our CI, I thought it was about `uvicorn`

**Comment by RobertoPrevato** [comment] 2020-12-10 14:54
I just verified that BlackSheep supports the latest version of `uvicorn` on Linux (I am not surprised about this because while writing the documentation and testing locally I've been working with the latest uvicorn all the time). I altro tried with `uvicorn[standard]`.
If you provide me a link to the source code of your benchmarks I can take a look.

Here the output of update command that install `uvicorn 0.13.0` and the command that runs the suite of 1125 tests:

```
pip install -U uvicorn
Collecting uvicorn
  Downloading https://files.pythonhosted.org/packages/2e/68/c282156b7b2ecdc9035d49ccf7fd5dd1e6161ca23463a7c4f1c87a8b6222/uvicorn-0.13.0-py3-none-any.whl (45kB)
     |████████████████████████████████| 51kB 2.0MB/s 
Collecting click==7.* (from uvicorn)
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting h11>=0.8 (from uvicorn)
  Using cached https://files.pythonhosted.org/packages/b2/79/9c5f5cd738ec2a9b26453b3093915c0999f24454e2773921025c03b5509e/h11-0.11.0-py2.py3-none-any.whl
Installing collected packages: click, h11, uvicorn
Successfully installed click-7.1.2 h11-0.11.0 uvicorn-0.13.0
WARNING: You are using pip version 19.2.3, however version 20.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

```
$ make test-cov
pytest --cov-report html --cov=blacksheep
========================================================================= test session starts =========================================================================
platform linux -- Python 3.9.0, pytest-5.4.1, py-1.8.0, pluggy-0.13.1
rootdir: /home/ra/projects/github/blacksheep, inifile: pytest.ini
plugins: asyncio-0.14.0, cov-2.10.1
collected 1125 items                                                                                                                                                  

itests/test_client.py ...................                                                                                                                       [  1%]
itests/test_server.py ........................................                                                                                                  [  5%]
tests/test_application.py ..................................................................................................................................... [ 17%]
...................................................................                                                                                             [ 23%]
tests/test_auth.py .................                                                                                                                            [ 24%]
tests/test_bindings.py .................................................................................................................                        [ 34%]
tests/test_contents.py .......................                                                                                                                  [ 36%]
tests/test_controllers.py ..................................                                                                                                    [ 39%]
tests/test_cookies.py ...........................                                                                                                               [ 42%]
tests/test_files_handler.py ......................                                                                                                              [ 44%]
tests/test_files_serving.py ..............................................................                                                                      [ 49%]
tests/test_headers.py ....................                                                                                                                      [ 51%]
tests/test_multipart.py ..........                                                                                                                              [ 52%]
tests/test_normalization.py ..........................................                                                                                          [ 55%]
tests/test_openapi_v3.py ...............                                                                                                                        [ 57%]
tests/test_pathutils.py ...............                                                                                                                         [ 58%]
tests/test_ranges.py .................................                                                                                                          [ 61%]
tests/test_requests.py ..............................                                                                                                           [ 64%]
tests/test_responses.py ...................................................................................................................                     [ 74%]
tests/test_router.py ..................................................................................................                                         [ 83%]
tests/test_templating.py ....................                                                                                                                   [ 84%]
tests/test_url.py ................                                                                                                                              [ 86%]
tests/test_utils.py ..............                                                                                                                              [ 87%]
tests/client/test_client.py ..............                                                                                                                      [ 88%]
tests/client/test_connection.py ..............                                                                                                                  [ 90%]
tests/client/test_cookiejar.py ..................................................                                                                               [ 94%]
tests/client/test_headers.py ...                                                                                                                                [ 94%]
tests/client/test_middlewares.py ....                                                                                                                           [ 95%]
tests/client/test_pool.py ........                                                                                                                              [ 95%]
tests/client/test_query.py ...........                                                                                                                          [ 96%]
tests/client/test_redirects.py ..................................                                                                                               [ 99%]
tests/client/test_timeouts.py ..                                                                                                                                [100%]

----------- coverage: platform linux, python 3.9.0-final-0 -----------
Coverage HTML written to dir htmlcov


======================================================================== 1125 passed in 11.99s ========================================================================
```

**Comment by RobertoPrevato** [comment] 2020-12-10 15:05
@waghanza 
I took a look at your build logs, and found your repository in GitHub.
https://github.com/the-benchmarker/web-frameworks/blob/master/python/blacksheep/requirements.txt.

I am able to reproduce the issue using a `requirements.txt` file like yours. I try to fix it by changing the requirements file, and I can do a PR to your repository if I find a solution.

**Comment by waghanza** [comment] 2020-12-10 15:05
The code is in https://github.com/the-benchmarker/web-frameworks/tree/master/python/blacksheep

perhaps a idea in https://the-benchmarker.semaphoreci.com/jobs/1fc7fd44-8041-46b8-b8e7-713d965e5b02#L338

**Comment by RobertoPrevato** [comment] 2020-12-10 15:22
This looks like a bug in `pip` itself to me and its [new resolver](https://docs.google.com/forms/d/e/1FAIpQLSe7crTan5HmokOThigd3XH49aez9A-H90uF7MpS8h9uFy6UPw/viewform).

I can reproduce the error of your build only when using the last version of pip (pip-20.3.1).
The problem if fixed if I change your requirements file to look like this:

```
blacksheep>=0.2.0,<0.3.0
gunicorn==20.0.4
uvicorn==0.13.0
uvloop==0.14.0; platform_system != "Windows"
```

The problem is originating in `gunicorn` without requirements, not in `uvicorn`. There is still a messy installation of `certifi` package, but the installation command works.

1. if I use `pip-20.2.3` everything works fine even without specifying the version of `gunicorn`, but the installation command displays a red error message that after October 2020 I might experience error installing packages
1. if I use the latest `pip-20.3.1` it doesn't work without specifying the version of gunicorn

**Comment by RobertoPrevato** [comment] 2020-12-10 15:27
I tried to push a branch to your repository to submit a PR, but I don't have rights to do so. So I won't submit a PR.

Closing this issue because it's not originating or depending on BlackSheep.

**Closed by RobertoPrevato** 2020-12-10 15:27 UTC

**Comment by RobertoPrevato** [comment] 2020-12-10 15:37
I submitted a bug report for the pip team, as [described here](https://docs.google.com/forms/d/e/1FAIpQLSe7crTan5HmokOThigd3XH49aez9A-H90uF7MpS8h9uFy6UPw/viewform).

**Comment by waghanza** [comment] 2020-12-10 15:38
Thanks. I have integrated your in the next update in https://github.com/the-benchmarker/web-frameworks/pull/3584 (results will be available tomorrow)

**Comment by waghanza** [comment] 2020-12-11 08:19
Results are updated https://github.com/the-benchmarker/web-frameworks#results @RobertoPrevato

**Comment by RobertoPrevato** [comment] 2020-12-11 08:39
Thank You! Interesting results!
